'use client'

import { useSyncExternalStore } from 'react'
import Link from 'next/link'
import { X, UserCircle } from 'lucide-react'
import { cn } from '@/lib/utils'
import { buttonVariants } from '@/components/ui/button'

// Matches auto-generated usernames like "joao_abc123" (trigger pattern)
function isAutoGeneratedUsername(username: string) {
  return /^.+_[a-z0-9]{6}$/.test(username)
}

const DISMISS_KEY = 'profile-banner-dismissed'
const DISMISS_EVENT = 'profile-banner-dismissed-change'

function subscribeToDismissed(onStoreChange: () => void) {
  window.addEventListener('storage', onStoreChange)
  window.addEventListener(DISMISS_EVENT, onStoreChange)

  return () => {
    window.removeEventListener('storage', onStoreChange)
    window.removeEventListener(DISMISS_EVENT, onStoreChange)
  }
}

function getDismissedSnapshot() {
  try {
    return localStorage.getItem(DISMISS_KEY) === '1'
  } catch {
    return false
  }
}

function getServerDismissedSnapshot() {
  return false
}

interface Props {
  avatarUrl: string | null
  username: string
}

export function ProfileSetupBanner({ avatarUrl, username }: Props) {
  const dismissed = useSyncExternalStore(
    subscribeToDismissed,
    getDismissedSnapshot,
    getServerDismissedSnapshot
  )

  const incomplete = !avatarUrl || isAutoGeneratedUsername(username)
  if (!incomplete || dismissed) return null

  function dismiss() {
    try {
      localStorage.setItem(DISMISS_KEY, '1')
    } catch {}

    window.dispatchEvent(new Event(DISMISS_EVENT))
  }

  return (
    <div className="flex items-center justify-between gap-4 rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30 px-4 py-3 text-sm">
      <div className="flex items-center gap-3">
        <UserCircle className="h-4 w-4 text-amber-600 dark:text-amber-400 shrink-0" />
        <span className="text-amber-800 dark:text-amber-300">
          Seu perfil ainda está incompleto — adicione uma foto e escolha seu @username.
        </span>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        <Link
          href="/dashboard/configuracoes"
          className={cn(buttonVariants({ variant: 'outline', size: 'sm' }), 'h-7 text-xs')}
        >
          Completar perfil
        </Link>
        <button
          onClick={dismiss}
          className="text-amber-600 hover:text-amber-800 dark:text-amber-400 dark:hover:text-amber-200 transition-colors"
          aria-label="Dispensar"
        >
          <X className="h-4 w-4" />
        </button>
      </div>
    </div>
  )
}
