'use client'

import { useSyncExternalStore } from 'react'
import Link from 'next/link'
import { X, ListChecks } from 'lucide-react'
import { cn } from '@/lib/utils'
import { buttonVariants } from '@/components/ui/button'

// Matches auto-generated usernames like "joao_abc123" (trigger pattern)
function isAutoGeneratedUsername(username: string) {
  return /^.+_[a-z0-9]{6}$/.test(username)
}

const DISMISS_KEY = 'profile-banner-dismissed'
const DISMISS_EVENT = 'profile-banner-dismissed-change'

function subscribeToDismissed(onStoreChange: () => void) {
  window.addEventListener('storage', onStoreChange)
  window.addEventListener(DISMISS_EVENT, onStoreChange)

  return () => {
    window.removeEventListener('storage', onStoreChange)
    window.removeEventListener(DISMISS_EVENT, onStoreChange)
  }
}

function getDismissedSnapshot() {
  try {
    return localStorage.getItem(DISMISS_KEY) === '1'
  } catch {
    return false
  }
}

function getServerDismissedSnapshot() {
  return false
}

interface Props {
  avatarUrl: string | null
  username: string
  hasPaymentMethod: boolean
  hasProject: boolean
}

export function SetupChecklistBanner({ avatarUrl, username, hasPaymentMethod, hasProject }: Props) {
  const dismissed = useSyncExternalStore(
    subscribeToDismissed,
    getDismissedSnapshot,
    getServerDismissedSnapshot
  )

  const pendingItems = [
    !avatarUrl || isAutoGeneratedUsername(username)
      ? { label: 'Complete seu perfil — adicione uma foto e escolha seu @username', href: '/dashboard/configuracoes' }
      : null,
    !hasPaymentMethod
      ? { label: 'Configure o recebimento de contribuições (Pix, PayPal, Wise...)', href: '/dashboard/configuracoes' }
      : null,
    !hasProject
      ? { label: 'Crie seu primeiro projeto para compartilhar com parceiros', href: '/dashboard/projetos/novo' }
      : null,
  ].filter((item): item is { label: string; href: string } => item !== null)

  if (pendingItems.length === 0 || dismissed) return null

  function dismiss() {
    try {
      localStorage.setItem(DISMISS_KEY, '1')
    } catch {}

    window.dispatchEvent(new Event(DISMISS_EVENT))
  }

  return (
    <div className="rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/30 px-4 py-3 text-sm">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-2">
          <ListChecks className="h-4 w-4 text-amber-600 dark:text-amber-400 shrink-0" />
          <span className="font-medium text-amber-800 dark:text-amber-300">Configuração do sistema pendente</span>
        </div>
        <button
          onClick={dismiss}
          className="text-amber-600 hover:text-amber-800 dark:text-amber-400 dark:hover:text-amber-200 transition-colors shrink-0"
          aria-label="Dispensar"
        >
          <X className="h-4 w-4" />
        </button>
      </div>
      <ul className="mt-2 space-y-1.5">
        {pendingItems.map((item) => (
          <li key={item.href + item.label} className="flex items-center justify-between gap-3">
            <span className="text-amber-800 dark:text-amber-300">{item.label}</span>
            <Link
              href={item.href}
              className={cn(buttonVariants({ variant: 'outline', size: 'sm' }), 'h-7 text-xs shrink-0')}
            >
              Completar
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}
